create dockerfile
fintegrate-practicom/inventory pull request #10
Opened 2024-04-02 06:33 UTC by braindi

מוזמנות להעיר.....

2024-04-03 20:05 UTC, nechamaLearn requested changes

2024-04-03 20:05 UTC, nechamaLearn commented on nest/.vscode/launch.json
כל התיקיה .vscode צריכה להכנס לgitignore

2024-04-03 20:05 UTC, nechamaLearn commented on nest/docker-compose.debug.yml
קובץ מיותר

2024-04-03 20:05 UTC, nechamaLearn commented on nest/docker-compose.yml
כרגע אין צורך בקובץ הזה

2024-04-03 20:05 UTC, nechamaLearn commented on nest/Dockerfile
> +EXPOSE 5000
זה הפורט עליו רץ הפרויקט?

2024-04-10 19:38 UTC, nechamaLearn requested changes
את צריכה כרגע למחוק לגמרי את התיקיה .vscode כדי שהיא תכנס להגדרה של gitignore

2024-04-14 09:09 UTC, nechamaLearn approved these changes

2024-04-14 09:24 UTC, braindi commented
היתה לי בעיה בהרצה
ועכשיו , אחרי שינויים , זה ב"ה עובד
מחכה לאישור

2024-04-14 09:26 UTC, nechamaLearn approved these changes

2024-04-14 09:28 UTC, merged