first-table-inventory
fintegrate-practicom/inventory pull request #15
Opened 2024-04-04 17:09 UTC by ChayaVitriol

2024-04-10 19:44 UTC, nechamaLearn requested changes
הקוד הזה עובד לך???

2024-04-10 19:44 UTC, nechamaLearn commented on nest/react/src/components/AllProducts.tsx
> +import React, { useState } from 'react';
אין סיבה לייבא את ריאקט
תייבאי רק מה שצריך מתוכו

2024-04-10 19:44 UTC, nechamaLearn commented on nest/react/src/components/AllProducts.tsx
> +            <ul>
זה המבנה של טבלה בmui?

2024-04-10 19:44 UTC, nechamaLearn commented on nest/react/src/components/Details.tsx
מה המטרה של הקומפוננטה הזו?

2024-05-27 09:50 UTC, nechamaLearn requested changes

2024-05-27 09:50 UTC, nechamaLearn commented on nest/react/src/components/tableInventory/SingalProduct.tsx
> +interface Component {
הייתי מוציאה את זה לקובץ חיצוני
שבו יש את כל הקבצים

2024-05-27 09:50 UTC, nechamaLearn commented on nest/react/src/components/tableInventory/AllProducts.tsx
> +        return components.map(component => `name: ${component.name}, price: ${component.price}`).join(', ');
??? למה לא להשתמש בקומפוננטה?

2024-06-10 08:33 UTC, nechamaLearn approved these changes

2024-06-10 08:33 UTC, nechamaLearn commented on nest/react/vite.config.ts
> +import { defineConfig } from 'vitest/config'
תוודאי שזה לא דרס דברים

2024-06-13 12:06 UTC, buzz-code commented on nest/react/src/components/tableInventory/SingalComponent.tsx
single ולא singal

2024-06-13 12:06 UTC, buzz-code commented on nest/react/src/components/tableInventory/SingalProduct.tsx
כנ״ל

2024-06-13 12:06 UTC, buzz-code commented on nest/react/src/components/tableInventory/SingalComponent.tsx
ככה זה צריך להראות? אין לזה עיצוב או משהו?

2024-06-13 12:06 UTC, buzz-code commented on nest/react/src/App.tsx
> +      productComponents: [{ name: "table leg", price: 10 }, { name: "table leg", price: 10 }],
למה כל המידע הזה נמצא בapp?
את הinterface תוציאי לקובץ נפרד
ואת הנתונים של הטבלה תיקחי מהbackend

2024-06-13 12:06 UTC, buzz-code commented on nest/react/package.json
יש פה הרבה מאד שינויים
אני בטוחה שחלקם הם טעות, למשל axios, הוא לא צריך להיות devDependency אלא dependency רגיל

2024-06-24 12:09 UTC, buzz-code commented on nest/react/src/components/tableInventory/AllProducts.tsx
> +                    <span key={index}>{componentName}, </span>
למה שלא תיצרי איזה map מהמערך שאת מקבלת?
וככה תוכלי לשלוף ברגע את הרכיבים המתאימים

2024-06-26 10:07 UTC, buzz-code approved these changes

2024-06-26 10:29 UTC, merged