Notification
fintegrate-practicom/inventory pull request #24
Opened 2024-04-11 11:47 UTC by rachelosh

pr on notification
קומפוננטה של התראות, עם התקנה של storybook וטסטים
בקובץ tsConfig יש איזו שהיא הערה שלא הבנתי, זה לא מפריע כרגע להרצת הפרוייקט,
תקיית stories זו תקיית דוגמא שנוצרת עם התקנת storybook השארתי אותה כדי שנוכל להעזר בה בהמשך

2024-04-15 08:21 UTC, nechamaLearn requested changes

2024-04-15 08:21 UTC, nechamaLearn commented on nest/react/src/stories/Configure.mdx
אפשר **לרוקן** את הקובץ הזה יחד עם המחיקה של הassets

2024-04-15 08:21 UTC, nechamaLearn commented on nest/react/src/stories/Button.stories.ts
תמחקי את הקבצים האלו שלא את יצרת
button, page, header

2024-04-15 10:50 UTC, rachelosh commented on nest/react/src/App.test.tsx
כשעשיתי טסטים בניתי אותו כדי לראות שהטסטים עובדים.... למחוק אותו?

2024-04-15 10:59 UTC, rachelosh commented on nest/react/src/stories/Button.stories.ts
אם למחוק את כל הקבצים, אני יכולה בעצם למחוק את כל התקיה stories?

2024-04-15 13:52 UTC, rachelosh commented on nest/react/src/componnents/notification/Notification.test.tsx
רוב המדריכים שקראתי עבדו עם סיומת ts/tsx

2024-05-20 08:17 UTC, nechamaLearn approved these changes

2024-05-20 11:33 UTC, merged