saving the arr components in redux
fintegrate-practicom/inventory pull request #29
Opened 2024-04-15 13:21 UTC by Rivkimi

2024-04-15 16:06 UTC, nechamaLearn requested changes
כמו שכתבתי לך בסלאק המיקום של הקבצים לא מקובל

2024-04-15 16:42 UTC, buzz-code commented on nest/react/src/components/app/store.ts
> +export const arrComponentStore = configureStore({
את מוסיפה עוד סטור? למה?

2024-04-16 11:06 UTC, buzz-code approved these changes

2024-05-02 12:34 UTC, buzz-code commented on nest/react/src/app/actions.ts
>      const updatedData = [...state.data];
למה בכל הפונקציות החזרת את הstate, ופה את משנה אותו?

2024-05-02 12:34 UTC, buzz-code commented on nest/react/src/features/product/productSlice.ts
> +}
לא צריך ליצור את הinterfacee מחדש, תעשי לו import מהדף של הcomponent

2024-05-20 11:34 UTC, merged