delete-package
fintegrate-practicom/inventory pull request #30
Opened 2024-05-13 14:13 UTC by braindi

מאחר והיו לי בעיות בבראנץ הקודם בעניין הפקג'ים
יצרתי בראנץ חדש.
אשמח לבדיקה בהקדם
תודה!

2024-05-20 12:23 UTC, nechamaLearn requested changes

2024-05-20 13:45 UTC, braindi commented on nest/src/entities/Product.ts
הוספתי ID

2024-05-20 13:45 UTC, braindi commented on nest/src/entities/Provider.ts
כנ"ל

2024-05-21 08:40 UTC, braindi commented
הוספתי טסטים לentitiies

2024-05-27 10:52 UTC, nechamaLearn approved these changes

2024-05-27 11:55 UTC, merged