addProduct
fintegrate-practicom/inventory pull request #33
Opened 2024-05-21 08:47 UTC by naama-dev

2024-05-27 11:05 UTC, nechamaLearn commented on nest/react/src/App.tsx
> +import  React,{ useState, Suspense  } from 'react';
אפשר לייבא רק את lasy אין עניין בהכל

2024-05-27 11:06 UTC, nechamaLearn commented on nest/react/src/App.tsx
מה קורה בעצם בקובץ הזה?
הוא מאוד לא ברור לי

2024-05-27 11:06 UTC, nechamaLearn commented on nest/react/src/App.tsx
מה שינית בו בעצם

2024-05-28 10:23 UTC, tzippykovalsky approved these changes

2024-05-28 11:02 UTC, tzippykovalsky approved these changes

2024-05-30 06:56 UTC, nechamaLearn requested changes

2024-05-30 06:56 UTC, nechamaLearn commented on nest/react/src/App.tsx
> +import  React,{ useState, Suspense  } from 'react';
????

2024-05-30 06:56 UTC, nechamaLearn commented on nest/react/src/components/AddProductForm.tsx
> +import React from "react";
לא לייבא את כל ריאקט
רק את מה שצריך מתוכו

2024-06-03 13:00 UTC, merged