implement-requests
fintegrate-practicom/inventory pull request #4
Opened 2024-03-28 17:29 UTC by Rivkimi

2024-03-28 17:43 UTC, rachelosh commented
רבקי הקוד שלך מהמהם, הלוואי על כולנו!!
צריך לעבוד קשה בשביל למצוא מה להעיר.....
אני לא יודעת מה הצורה הנכונה לעבוד, אבל אפשר לוותר בקריאות שרת על try ו catch?
קריאות שרת זה דבר שלוקח זמן, והן גם יכולות ליפול בקלות.
האמת היא שהיה לי קשה למצוא עוד משהו, רק כמה תהיות
בפרויקטים שעשינו יצרנו תקיית config, ושם היו כל קבצי ההגדרות למינהם, יכול להיות שעדיף ליצור תקיה כזו.
ודרך אגב בכונה השארת את הערות?

2024-03-28 19:43 UTC, nechamaLearn requested changes
אז כמו שכתבתי, הURLs בproduct  ובcomponent זהים
חייבים להפריד אותם

2024-03-28 19:43 UTC, nechamaLearn commented on nest/react/src/Api-Requests/component/Component.ts
> +    return axios.delete(`${baseUrl}/api/inventory/${componentId}`);
מה ההבדל בין הלינק הזה לproduct?

2024-03-28 19:43 UTC, nechamaLearn commented on nest/react/src/Api-Requests/product/Product.ts
> +    return axios.delete(`${baseUrl}/api/inventory/${productId}`);
כנ"ל זה נראה לינק זהה

2024-03-28 19:43 UTC, nechamaLearn commented on nest/react/src/Api-Requests/config.ts
> +//url from api
הייתי מעבירה את זה למשתנה סביבה

2024-03-30 19:41 UTC, buzz-code requested changes

2024-03-30 19:41 UTC, buzz-code commented on package.json
@Rivkimi 
נשמע לי חשוד שהיית צריכה להוסיף את הקובץ הזה, הוא לא קיים כבר בפרוייקט?
אולי את עובדת עם גרסה ישנה ולא מעודכנת שלו?

2024-04-04 14:05 UTC, nechamaLearn approved these changes

2024-04-07 14:09 UTC, merged