Dispatch addproduct
fintegrate-practicom/inventory pull request #45
Opened 2024-06-04 08:02 UTC by chayakno

הוספת מוצר---
מחכה לתמונות.

2024-06-06 23:33 UTC, nechamaLearn requested changes

2024-06-06 23:33 UTC, nechamaLearn commented on nest/react/src/App.tsx
> +      {/* <div>
תמחקי את ההערה לגמרי

2024-06-06 23:33 UTC, nechamaLearn commented on nest/react/src/components/AddProductForm.tsx
>      Pictures: FileList
מה זה הtype הזה?

2024-06-06 23:33 UTC, nechamaLearn commented on nest/react/src/components/ComponentForm.tsx
> +        console.log();
מה המטרה בזה?

2024-06-06 23:35 UTC, nechamaLearn commented
אני שמה לב שיש 2 PRים שמכילים את אותו החומר בדיוק 43 ו45 מה ההבדל בינהם????

2024-06-13 09:49 UTC, chayakno commented
ישנו קומיט מעודכן ל-2 הבנצים ביחד
היתה טעות  ביצירת הברנץ השני,נוצר מתוך ברנץ 43
אשמח לאישור

2024-06-17 10:40 UTC, nechamaLearn requested changes

2024-06-18 09:00 UTC, chayakno commented
קומיט כולל שמירת נתוני התמונות...

2024-06-18 10:58 UTC, nechamaLearn commented on nest/react/src/components/AddProductForm.tsx
>      Pictures: FileList
השאלה שלי לא הובנה
אני שואלת על הtype של FileList

2024-06-18 10:58 UTC, nechamaLearn commented
עדכנתי הערה אחת

2024-06-18 11:03 UTC, chayakno commented
בקשר להערה-על הtype של FileList
לא אני יצרתי את הטופס אני יצרתי את הפונקציתהשמירה שלה
במקרה אני יודעת שזאתי שיצרה את טופס הוספת מוצר שינתה את הtype הזה והעלתה קומיט עם השינויים

2024-06-23 06:16 UTC, nechamaLearn approved these changes

2024-06-23 09:39 UTC, merged