example show products
fintegrate-practicom/inventory pull request #52
Opened 2024-06-21 10:36 UTC by Rivkimi

2024-06-24 09:53 UTC, buzz-code commented on nest/react/src/components/showProducts/AllProducts.tsx
> +export default function SpacingGrid() {
למה קוראים לקומפוננטה בכזה שם?

2024-06-24 09:53 UTC, buzz-code commented on nest/react/src/components/showProducts/AllProducts.tsx
> +      //setProducts([res.data]);
בבקשה תמחקי את ההערה, ואת הconsole.log

2024-06-24 09:53 UTC, buzz-code commented on nest/react/src/components/showProducts/AllProducts.tsx
> +      alert(err);
לא מעלים alert לפרודקשן
מקסימום console.log

2024-06-24 09:53 UTC, buzz-code commented on nest/react/src/components/showProducts/AllProducts.tsx
> +  const [spacing, setSpacing] = useState(2);
מה התפקיד של המשתנה הזה?

2024-06-24 09:53 UTC, buzz-code commented on nest/react/src/components/showProducts/signleProduct.tsx
שגיאת כתיב בשם של הקובץ, שם הקובץ לא תואם לקומפוננטה

2024-06-24 09:53 UTC, buzz-code commented on nest/react/src/components/showProducts/signleProduct.tsx
> +        ))}
אין תמונות?

2024-06-24 12:18 UTC, buzz-code commented on nest/react/src/components/showProducts/AllProducts.tsx
> +import ProductCard from './singleProduct';
למה השם של הקובץ שונה מהשם של הקומפוננטה?

2024-06-27 18:36 UTC, nechamaLearn requested changes

2024-06-27 18:36 UTC, nechamaLearn commented on nest/react/src/components/showProducts/singleProduct.tsx
> +              // <img src={image.src} alt={image.alt} key={image.id} />
מצטרפת לשאלה של הדסה, מה את עושה כאן בעצם?

2024-06-30 05:48 UTC, buzz-code commented on nest/react/src/app/actions.ts
>  }
זה לא שינוי טוב
תשאירי את הinteface הקיים, של item
למה הורדת אותו?

2024-06-30 05:48 UTC, buzz-code commented on nest/react/package.json
למה?

2024-06-30 05:48 UTC, buzz-code commented on nest/react/src/components/showProducts/singleProduct.tsx
> +  const qes = "totalPrice" in product;
מה המשמעות של השם הזה?

2024-06-30 12:07 UTC, buzz-code commented on nest/react/src/app/actions.ts
> +export const setData = <T extends Item>(state: State<T>, action: PayloadAction<T>) => {
כנראה זה בטעות, action.payload צריך להיות מערך, לא?

2024-06-30 13:37 UTC, buzz-code approved these changes

2024-07-02 02:38 UTC, nechamaLearn approved these changes

2024-07-02 06:49 UTC, merged