create entities
fintegrate-practicom/inventory pull request #7
Opened 2024-04-02 06:07 UTC by braindi

בהצלחה בבדיקה!!!

2024-04-03 20:07 UTC, nechamaLearn requested changes
יש עוד הרבה הגדרות שאפשר להגדיר למבנים האלו
כמו סוג, אורך טקסט וכו'

2024-04-10 06:58 UTC, braindi commented
הוספתי הגדרות נוספות

2024-04-11 08:33 UTC, braindi commented on package-lock.json
בשביל ליצור את הentities התקנתי ספריות, ולכן הpackage-lock.json והpackage-json השתנו,
אם אני אמחק את השינויים בקבצים הנ"ל, כשיעשו npm i הוא לא יוריד את הספריות האלו
האם למחוק בכל זאת????

2024-04-16 11:20 UTC, braindi commented
יצרתי שינויים רבים בentities בהתאם לטפסים של הוספת מוצר ורכיב
אשמח לבדיקה בהקדם האפשרי
בנות תלויות בו
תודה!

2024-04-16 11:28 UTC, buzz-code commented on nest/src/entities/Component.ts
> +    @Length(3, 20, { message: "name must be at least 3 characters" })
שימי לב שהגבלת גם אורך מקסימום, תצייני בתגובה גם אותו
name must be between ...

2024-04-16 11:28 UTC, buzz-code commented on nest/src/entities/Component.ts
> +    @Column({ nullable: false })
אם השדה הוא nullable, תוסיפי לו גם ולידציה שהוא לא null
תעשי את זה בכל השדות שהם לא nullable

2024-04-16 11:28 UTC, buzz-code commented on nest/src/entities/Component.ts
> +    componentStock: number = 0;
על שני השדות כתבת את אותה הערה
אבל הערכים שלהם הם שונים - 0 ו 1

2024-04-16 11:28 UTC, buzz-code commented on nest/src/entities/Component.ts
> +    @Length(3, 15, { message: "must be at least 3 characters" })
כנ"ל

2024-04-16 11:28 UTC, buzz-code commented on package-lock.json
שימי לב שיש לך 2 קבצי package json & package lock json
בתוך התיקיה של nest, ומחוץ לה
הקבצים שבחוץ מיותרים, תמחקי אותם

2024-04-16 11:31 UTC, braindi commented on nest/src/entities/Component.ts
> +    @Column({ nullable: false })
מה זאת אומרת??

2024-05-09 13:48 UTC, nechamaLearn requested changes

2024-05-09 13:48 UTC, nechamaLearn commented on nest/src/entities/Product.ts
> +    isActive: boolean = true;
את בטוחה שככה כותבים את זה?

2024-05-09 14:03 UTC, braindi commented on nest/src/entities/Product.ts
> +    isActive: boolean = true;
שאלתי את הדסה האם זה נכון והיא אמרה לי כמה דברים קטנים לשנות ושיניתי בהתאם למה שהיא אמרה
מה נראה לא נכון???

2024-05-27 12:19 UTC, closed without merging